### ISSUE TITLE
ivorysql_ora/Makefile: ifeq($(with_libxml),yes) evaluated before with_libxml is defined — -lxml2 dropped, link fails (regression from #1370)

### ISSUE THREAD

**Issue by Aias00** [IvorySQL/IvorySQL#1541]
### Summary

In `contrib/ivorysql_ora/Makefile`, the block

```make
ifeq ($(with_libxml),yes)
SHLIB_LINK += -lxml2
endif
```

is placed **before** the `include $(top_builddir)/src/Makefile.global` that defines `with_libxml`. GNU make evaluates `ifeq` while parsing, so at that point `with_libxml` is still empty, the condition is false, and `-lxml2` is never added to `SHLIB_LINK` — even on builds configured with `--with-libxml`.

The result: `ivorysql_ora` compiles (the headers are found via `--with-libxml`'s CPPFLAGS) but fails to link, with undefined libxml2 symbols.

This is a regression introduced by #1370, which wrapped the previously-unconditional `SHLIB_LINK += -lxml2` in the `ifeq` guard but placed the guard above the includes.

### How to reproduce

```sh
./configure --prefix=$PWD/build_install --with-libxml --with-icu --with-ssl=openssl --with-readline
make -j
make -C contrib/ivorysql_ora
```

### Current (broken) behavior

The final link command for `ivorysql_ora.dylib`/`.so` contains no `-lxml2`:

```
gcc ... -bundle -o ivorysql_ora.dylib  src/ivorysql_ora.o ... src/xml_functions/ora_xml_functions.o ... \
  -bundle_loader ../../src/backend/postgres     # <-- no -lxml2
Undefined symbols for architecture arm64:
  "_xmlXPathNewContext", referenced from: _ivy_xml_xpath in ora_xml_functions.o
  "_xmlXPathRegisterNs", referenced from: _register_ns_from_csting in ora_xml_functions.o
  ...
ld: symbol(s) not found for architecture arm64
```

`make -p` confirms the dropped flag:

```
SHLIB_LINK = $(BE_DLLLIBS)        # == -bundle_loader .../postgres, no -lxml2
with_libxml = yes                 # defined, but too late for the ifeq
```

### Root cause

Makefile ordering (current master `contrib/ivorysql_ora/Makefile`, lines ~89–105):

```make
ifeq ($(with_libxml),yes)     # evaluated NOW — with_libxml is empty
SHLIB_LINK += -lxml2          # skipped
endif

PG_CPPFLAGS += -I$(top_srcdir)/src/pl/plisql/src

ifdef USE_PGXS
...
else
subdir = contrib/ivorysql_ora
top_builddir = ../..
include $(top_builddir)/src/Makefile.global     # with_libxml defined HERE (too late)
include $(top_srcdir)/contrib/contrib-global.mk
endif
```

GNU make resolves `ifeq` at parse time, in file order. Because `with_libxml` is set by `src/Makefile.global`, any `ifeq ($(with_libxml),...)` must come **after** that include.

Note this is distinct from #1353 (an environment issue where libxml2-devel is not installed on openEuler). Here the library is available and `--with-libxml` is set; the flag is dropped by a Makefile ordering bug.

### Expected behavior / suggested fix

Move the `with_libxml`-dependent block (and `PG_CPPFLAGS`) to **after** the includes so the variable is already defined:

```make
ifdef USE_PGXS
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
else
subdir = contrib/ivorysql_ora
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
endif

ifeq ($(with_libxml),yes)
SHLIB_LINK += -lxml2
endif

PG_CPPFLAGS += -I$(top_srcdir)/src/pl/plisql/src
```

Caveat to verify: under `USE_PGXS` (out-of-tree) builds, `PG_CPPFLAGS` is normally expected to be set before `include $(PGXS)`. If `PG_CPPFLAGS` is moved after the includes, PGXS consumers may need it set earlier — so a reviewer should confirm the PGXS path still picks up the plisql include, or split the two (`PG_CPPFLAGS` before includes, `SHLIB_LINK`/`ifeq` after).

### Environment

- IvorySQL: master @ d4661fb1d89 (5beta1 / PG 19devel)
- OS: macOS 26 (Darwin 25.2.0, arm64)
- Compiler: Apple clang 17.0.0
- configure: `--with-libxml --with-icu --with-ssl=openssl --with-readline`

**Comment by jiaoshuntian** [comment]
ths fixes is here: #1475
